# Generated by Django 2.0.3 on 2018-03-24 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('evaluator', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('1', 'Administrator'), ('2', 'Client user | Company'), ('3', 'Normal user | Construction worker')], max_length=100, null=True)),
                ('id_card', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('working_years_cc', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('experiences', models.CharField(blank=True, max_length=100, null=True)),
                ('no_coworker', models.CharField(blank=True, max_length=100, null=True)),
                ('disability', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('family_member', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('no_siblings', models.CharField(blank=True, max_length=100, null=True)),
                ('no_relative', models.CharField(blank=True, max_length=100, null=True)),
                ('current_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('training', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_training', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expect_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evaluationmasters',
            name='user_evaluations',
            field=models.ManyToManyField(blank=True, to='users.UserProfile'),
        ),
    ]
